version: 0.2

phases:
  install:
    commands:
      - echo "Instalando..."
  pre_build:
    commands:
      - echo "Iniciando sesión en Docker Hub..."
      - echo "dckr_pat_uj1FbNd0vTJHHWymPi0uvIdjD8Y" | docker login -u "sebas1docker" --password-stdin
  build:
    commands:
      - echo "Construyendo la imagen..."
      - docker build -t sebas1docker/flask-app:latest ./app
  post_build:
    commands:
      - echo "Subiendo la imagen a Docker Hub..."
      - docker push sebas1docker/flask-app:latest

artifacts:
  files:
    - '**/*'